title: 连思鑫的博客
subtitle: 科技改变生活
description: 这是一个个人的博客网站
keywords: 博客
author: 连思鑫
language: zh-CN
timezone: Asia/Shanghai
url: https://jinbilianshao.github.io/
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: fluid
deploy:
  type: git
  repository: git@github.com:JinBiLianShao/jinbilianshao.github.io.git
  branch: master
  token: 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
search:
  path: search.xml
  field: post
server:
  port: 4001
  compress: true
  header: true
auto-issue:
  owner: JinBiLianShao
  repo: git@github.com:JinBiLianShao/jinbilianshao.github.io.git
  auth: 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
  userAgent: hexo-auto-iissue
  sort_by: date
  withGitalk: false
  delay: 2000

# 已禁用 Hexo 的代码高亮，交由 Fluid 主题处理
highlight:
  enable: false
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  exclude_languages:
    - example
  wrap: true
  hljs: false

prismjs:
  enable: false
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''


# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'

markdown:
  preset: 'default'
  render:
    html: true
    breaks: false
    linkify: true
  plugins:
    - '@traptitech/markdown-it-katex'

# 新增：看板娘配置
live2d:
  enable: true
  # scriptFrom: local # 本地加载，需要 npm install hexo-helper-live2d
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  tagMode: false # 是否仅在有 live2d 标签的页面加载
  debug: false # 是否在控制台输出日志
  model:
    # 使用 npm install live2d-widget-model-shizuku 安装
    use: live2d-widget-model-shizuku
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    position: right # 显示在右下角
    width: 150
    height: 300
    hOffset: 0
    vOffset: -20
  mobile:
    show: true # 移动端是否显示
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.9

# 指定自定义 .js 文件路径，支持列表；路径是相对 source 目录，如 /js/custom.js 对应存放目录 source/js/custom.js
# Specify the path of your custom js file, support list. The path is relative to the source directory, such as `/js/custom.js` corresponding to the directory `source/js/custom.js`
custom_js:
  - /js/disable-math-rendering.js

# 指定自定义 .css 文件路径，用法和 custom_js 相同
# The usage is the same as custom_js
custom_css:
  - /css/custom.css