title: 连思鑫的博客
subtitle: 科技改变生活
description: 这是一个个人的博客网站
keywords: 博客
author: 连思鑫
language: zh-CN
timezone: Asia/Shanghai
url: https://jinbilianshao.github.io/
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: fluid
deploy:
  type: git
  repository: git@github.com:JinBiLianShao/jinbilianshao.github.io.git
  branch: master
  token: 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
search:
  path: search.xml
  field: post
server:
  port: 4001
  compress: true
  header: true
auto-issue:
  owner: JinBiLianShao
  repo: git@github.com:JinBiLianShao/jinbilianshao.github.io.git
  auth: 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
  userAgent: hexo-auto-iissue
  sort_by: date
  withGitalk: false
  delay: 2000

  highlight:
    enable: false
    auto_detect: false
    line_number: true
    line_threshold: 0
    tab_replace: ''
    exclude_languages:
      - example
    wrap: true
    hljs: false
  prismjs:
    enable: false
    preprocess: true
    line_number: true
    line_threshold: 0
    tab_replace: ''


# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'

